main_dim: 768
main_attn_num: 12
moe_layer_num: 8
router_moe_layer_num: 8
aux_dim: 256
aux_attn_num: 8
aux_layer_num: 6
aux_spec_attn: false
routed_expert_num: 60
expert_num_per_token: 4
router_group_num: 1
balance_loss_factor: 0.01
main_balance_loss_coeff: 0.1
routed_scaling_factor: 1.0
expert_dim: 512
shared_expert: false
shared_expert_dim: 512
first_k_layer_dense: 2
last_k_layer_dense: 2
ffn_factor: 2.0
block_size: 16
vocab_size: 50304
eot_idx: 50256
layer_wise_router: false
group_wise_router: false
token_keys: true
token_router_bias: true
predict_type: 1
no_router_values: true
reweight_steps: 64
reweight_min: 0.2
reweight_max: 2.0
grad_reweight: true
world_size: 1

seq_len: 2048
init_std: 0.02
max_lr: 3.0e-4
aux_max_lr: 1.5e-4
theta: 10000.0
weight_decay: 0.1
adam_betas: [0.9, 0.95]
grad_clip: 1.0
norm_eps: 1.0e-8
adam_eps: 1.0e-8
dtype: "bfloat16"
tied_vocab_emb: true
flex_attn_spec_kernel: true
zero_optimizer: false
grouped_gemm_option: "for_loop"
grouped_gemm_func: false
grouped_gemm_checkpoint: false
kernel_options:
  BLOCK_M: 64
  BLOCK_N: 64
  BLOCK_M1: 32
  BLOCK_N1: 64
  BLOCK_M2: 64
  BLOCK_N2: 32

train_bin: "/root/autodl-tmp/llm.c/dev/data/fineweb10B/fineweb_train_*.bin"
val_bin: "/root/autodl-tmp/llm.c/dev/data/fineweb10B/fineweb_val_*.bin"
router_batch_size: 4
router_sum_steps: 16
aux_batch_size: 16
aux_sum_steps: 4
router_num_steps: 1000
router_warmup_steps: 100
router_cooldown_steps: 1000
batch_size: 4
sum_steps: 16
num_steps: 10000
warmup_steps: 100
cooldown_steps: 1000
val_every: 50
val_steps: 20
min_lr_ratio: 0.01
save: false
cooldown_save: false
overfit: false
mixed_precision: true
scaler: true
model_compile: false
wandb_mode: "disabled"
load_from_checkpoint: false
checkpoint_path: " "
load_model: false
load_data: false
load_optimizer: false
profiler: false
profiler_step: 5
memory_profiler: false
memory_profiler_start_step: 6
memory_profiler_end_step: 8